spring.application.name=auctionSystem
server.port=8080

# IAM DATABASE
app.datasource.iam.url=jdbc:sqlite:IAM.db
app.datasource.iam.driver-class-name=org.sqlite.JDBC
app.jpa.iam.dialect=org.hibernate.community.dialect.SQLiteDialect
app.jpa.iam.ddl-auto=none

# AUCTION DATABASE
app.datasource.auction.url=jdbc:sqlite:AUCTION.db
app.datasource.auction.driver-class-name=org.sqlite.JDBC
app.jpa.auction.dialect=org.hibernate.community.dialect.SQLiteDialect
app.jpa.auction.ddl-auto=update

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always