spring.application.name=auctionSystem
server.port=8080

# IAM DATABASE
app.datasource.iam.url=jdbc:sqlite:IAM.db
app.datasource.iam.driver-class-name=org.sqlite.JDBC
app.jpa.iam.dialect=org.hibernate.community.dialect.SQLiteDialect
app.jpa.iam.ddl-auto=update

# AUCTION DATABASE
app.datasource.auction.url=jdbc:sqlite:AUCTION.db
app.datasource.auction.driver-class-name=org.sqlite.JDBC
app.jpa.auction.dialect=org.hibernate.community.dialect.SQLiteDialect
app.jpa.auction.ddl-auto=update

# CATALOGUE DATABASE
app.datasource.catalogue.url=jdbc:sqlite:CATALOGUE.db
app.datasource.catalogue.driver-class-name=org.sqlite.JDBC
app.jpa.catalogue.dialect=org.hibernate.community.dialect.SQLiteDialect
app.jpa.catalogue.ddl-auto=update

# PAYMENT DATABASE
app.datasource.payment.url=jdbc:sqlite:PAYMENT.db
app.datasource.payment.driver-class-name=org.sqlite.JDBC
app.jpa.payment.dialect=org.hibernate.community.dialect.SQLiteDialect
app.jpa.payment.ddl-auto=update

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# =========================
# RABBITMQ CONFIG
# =========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.simple.acknowledge-mode=auto
logging.level.org.springframework.amqp=DEBUG