package com.BidTech.auctionSystem.chatbot;

/**
 * ChatMessage — a single message in a conversation with the AI chatbot.
 *
 * <p>This DTO is used in two places:
 * <ol>
 *   <li>In {@link ChatRequest#getHistory()} — the conversation history sent from the browser</li>
 *   <li>In the Ollama API request body — the messages array sent to llama3.2</li>
 * </ol>
 *
 * <p>Ollama expects the role to be one of: "system", "user", or "assistant".
 * The "system" role is used for the injected system prompt (never sent from the browser).
 * The "user" role is for messages typed by the human.
 * The "assistant" role is for responses generated by the model.
 */
public class ChatMessage {

    /**
     * The role of the message sender.
     * Must be one of: "system", "user", "assistant".
     * "system" is reserved for the backend-injected system prompt.
     */
    private String role;

    /**
     * The text content of the message.
     * For "system" messages this is the injected prompt with live data.
     * For "user" messages this is what the user typed.
     * For "assistant" messages this is what Ollama responded.
     */
    private String content;

    /** Default no-arg constructor required for JSON deserialisation. */
    public ChatMessage() {}

    /**
     * Convenience constructor for building messages programmatically in ChatService.
     *
     * @param role    the message role ("system", "user", or "assistant")
     * @param content the message text
     */
    public ChatMessage(String role, String content) {
        this.role = role;
        this.content = content;
    }

    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }
}
